---
title: "New functions of StatComp20072"
author: "Fangjuan Ye"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{New functions of StatComp20072}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

##Two new function
_rSim_ is used in VAR system which is an explicit loop.
_Mnrom_ is used to generate mixed normal distribution with different means and variance


The source R code for _rSim_ is as follows:
```{r,eval=FALSE}

rSim<-function(coeff,errors){
  simdata<-matrix(0,nrow(errors),ncol(errors))
 for (i in 2:nrow(errors)){
  simdata[i,]=coeff %*% simdata[(i-1),]+errors[i,]
  }
  return(simdata)
}
```

##Example of rSim
```{r,eval=T}
library(StatComp20072)
a<-matrix(c(0.5,0.1,0.1,0.5),nrow=2)
u<-matrix(rnorm(100),ncol=2)
rData<-rSim(a,u)
rData
```





The source R code for _Mnorm_ is as follows:
```{r,eval=FALSE}
Mnorm<-function(p,N,mu0,sigma0){
  sigma1<-sample(sigma0,size = N,replace = T,prob = p)
  mu1<-sample(mu0,size = N,replace = T,prob = p)
  x<-rnorm(N,mu1,sigma1) 
  return(x)
}
```

##Example of Mnorm
```{r,eval=T}
p<-c(0.2,0.2,0.1,0.5)
sigma0<-c(1,2,4,5)
mu0<-c(1,3,4,2)
N<-20
Mnorm(p,N,mu0,sigma0)
```

