# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Generate the standard Laplace distribution with a normal increment using Rcpp
#' @description  Generate the standard Laplace distribution with a normal increment using Rcpp
#' @param N the simulation times
#' @param sigma the standard error
#' @param x0 the intial value
#' @return a random samples \code{n}
#' @examples
#' \dontrun{
#' sigma<-1
#' x0<-25
#' N<-3000
#' MC<-MetropolisC(sigma,x0,N)
#' }
#' @export
MetropolisC <- function(sigma, x0, N) {
    .Call('_StatComp20072_MetropolisC', PACKAGE = 'StatComp20072', sigma, x0, N)
}

